### PR TITLE
FIX: Minor jshint issues

### PR DESCRIPTION
**Pull request by juliandoucette**
- Because you do not reference handler elsewhere, I am assuming that it is supposed to be a local variable.
- It would be nice to indicate that top is a global variable for readability

Minor issues. Feel free to close if you don't agree. Thanks :) .

### CODE REVIEW

**Comment by WebReflection** [comment]
I haven't leaked a variable in ages ... damn it me!!!

I also usually use jshint, weird this passed through. Please put the handler in the for loop, I'm sure it was there before and got lost in some quick refactoring.

OK for the top, I find it funny window is OK but `top` isn't, haven't realized that.

Cheers!

**Comment by WebReflection** [comment]
There were other lint gotchas and jshint was disabled indeed for dunno which reason.

Version 0.3.3 is out and it has no warnings anymore.

Cheers

**Comment by juliandoucette** [comment]
Hey, sorry for the delay. Did you still want me to update this patch or did you get it in your latest commit?

**Comment by WebReflection** [comment]
all in already, thanks

**Pull request closed without merging**
