### PR TITLE
Added defaultPrevented and relatedTarget event properties

### PR DESCRIPTION
**Pull request by Finesse**
This properties are supported by IE9 but not supported by IE8.

The `defaultPrevented` property didn't work despite this code:

```javascript
preventDefault: valueDesc(function () {
    if (this.cancelable) {
        this.defaultPrevented = true;
        this.returnValue = false;
    }
})
```

Now it works.

### CODE REVIEW

**Comment by WebReflection** [comment]
FYI you need to just update the `./src/` folder, the rest comes up automatically after running `make`.

IIRC (it's an old repo) to run `make` you need to run `make dependencies` first.

Anyway, this looks fine but I don't see any test so it won't land here until you've added two little test 😉 

Thank you!

**Comment by FinesseRus** [comment]
@WebReflection There are no instructions in your repository how to build and test, so it's easier for me to build and test by myself.

I will make tests in the likeness of existing tests and try to run them.

**Comment by WebReflection** [comment]
> There are no instructions in your repository how to build and test

I know, nobody cared so far ... IE8 has been abandoned too in the meanwhile (you should as well)

Tests are simple to understand, `make web` should spin the server to launch through your **real** IE8 instance and verify that everything is green following test instructions.

**Comment by FinesseRus** [comment]
I've added the tests

**Comment by WebReflection** [comment]
will double check later on and test/republish.

Thanks

**Comment by FinesseRus** [comment]
Thank you for quick response! I thought I would have to wait months for the merge.

Do you mean publish the new version to the CDN when you say "republish"? If no, when will you publish the new publish the new version to the CDN?

**Comment by WebReflection** [comment]
yes, I mean updating all the things around and push new revision/version tags (so that the CDN will catch up too)

**Comment by FinesseRus** [comment]
I would be very glad to abandon IE8 but in some tardy regions (including my region) IE8 is still actual, especially within government organisations. In my region IE8 is even more popular than IE9.

**Comment by WebReflection** [comment]
Especially government organisations should update their obsolete, deprecated, insecure, most likely illegal, operating systems ... but I know you've no power over that decision.

Windows XP should never be used by the government, they have gazillion **free** and more secure alternatives. It sadden me there are still places IE8 is relevant.

**Pull request merged**
