### PR TITLE
Added HTMLElement and Document polyfills

### PR DESCRIPTION
**Pull request by Finesse**
There are no `HTMLElement` and `Document` variables in IE8 but they are in IE9. They are required in some cases, for example:

```javascript
if (!(element instanceof HTMLElement)) {
    throw new Error('HTM element expected');
}
element.style.color = 'red';
```

I've made a code that adds this variables:

```javascript
window.HTMLElement = window.Element;
window.Document = window.HTMLDocument;
```

It is not perfect but it lets us don't give a fuck that there is no `HTMLElement` in IE8.

### CODE REVIEW

**Comment by WebReflection** [comment]
I'm fine with the `HTMLElement` one but I'm not sure I understand why `window.Document = window.HTMLDocument;` is needed ?

**Comment by FinesseRus** [comment]
@WebReflection Just in case. I've never used `Document` in my practice. I think it is not so important.

**Comment by WebReflection** [comment]
I think the correct way is to `window.HTMLDocument` so I wouldn't pollute unnecessarily the global here.

Mind dropping the second assignment?

It's also quite possible this is a breakingchange for any library out there that would trust `HTMLElement` is not there to opt-in for `IE8` but hopefully a minor release bump would do.

**Comment by FinesseRus** [comment]
I can't fully understand what you mean.

I don't care a lot about `window.Document = window.HTMLDocumen` assignment. Do with it what you want.


> It's also quite possible this is a breakingchange for any library out there that would trust HTMLElement is not there to opt-in for IE8

I think that the goal of this polyfill is to make IE8 act like IE9 so it will be OK if a library treats IE8 like IE9.

**Comment by WebReflection** [comment]
> I don't care a lot about window.Document = window.HTMLDocumen assignment. Do what you want with it.

I want you to remove it from this PR 😉 

> I think that the goal of this polyfill is to make IE8 act like IE9 so it will be OK if a library treats IE8 like IE9.

it was rather a statement, not an argument against this PR.

**Comment by FinesseRus** [comment]
> I want you to remove it from this PR 😉

Done

**Pull request merged**
