### PR TITLE
Support pageX, pageY propertie at Event

### PR DESCRIPTION
**Pull request by sculove**
IE8 does not support pageX/pageY properties at Event.
I add pageX,pageY properties.
I also add testcase.

reference #31

### CODE REVIEW

**Comment by sculove** [comment]
I'd like to introduce WebReflection/ie8 to iScroll.
WebReflection/ie8 is appropriate to use IE8 with iscroll.

Hopefully this pr will be merged. thank you

**Comment by WebReflection** [comment]
I'm afraid this PR won't work as it is.

First of all, you really don't want to compute those properties per each event, you want to eventually compute them once and lazily, only if accessed.

This repo is configured in a way that `src/ie8.js` is the only file you need to change. Any change in the build folder will be lost next deploy.

That being said, I'm not sure this should be part of [DOM4](https://github.com/WebReflection/dom4#dom4) rather than IE8.

**Comment by sculove** [comment]
@WebReflection ok. I got it. Thank you

**Comment by WebReflection** [comment]
I've just pushed (but not published) a smarter version of `pageX` and `pageY`.

Mind giving it a spin and tell me if it works for you?

https://github.com/WebReflection/ie8/blob/master/build/ie8.max.js

**Comment by sculove** [comment]
@WebReflection ok I check it. thanks

**Comment by sculove** [comment]
@WebReflection Oh~! very good. perfect! 
Hopefully, smart version will be merged.

**Comment by WebReflection** [comment]
flagged and published as `0.4.0` ... it should be available via CDN soon.

**Comment by WebReflection** [comment]
I'll close this since not useful anymore. I'll keep your test in mind (and try to automate that if possible, the interactive test is a bit weird :-) )

**Pull request closed without merging**
